version: "3.7"
services:
  envoy:
    image: envoyproxy/envoy:v1.13.1
    networks:
      - envoymesh
    ports:
      - "8443:8443"
      - "9901:9901"
    expose:
      - "8443"
      - "9901"
    volumes:
      - ${PWD}/example/envoy-config.yaml:/etc/envoy/config.yaml
      - ${PWD}/certs/envoy-client.crt:/etc/envoy/tls/envoy-client.crt
      - ${PWD}/certs/envoy-client.key:/etc/envoy/tls/envoy-client.key
    command:
      - envoy
      - -c
      - /etc/envoy/config.yaml
  marin3r:
    build:
      context: ./
      args: [RELEASE]
    networks:
      envoymesh:
        aliases:
          - marin3r
    ports:
      - "18000:18000"
      - "19001:19001"
    expose:
      - "18000"
      - "19001"
    environment:
      - KUBECONFIG=/etc/marin3r/kubeconfig
    volumes:
      - ${HOME}/.kube/config:/etc/marin3r/kubeconfig
      - ${PWD}/certs/marin3r-server.crt:/etc/marin3r/tls/server.crt
      - ${PWD}/certs/marin3r-server.key:/etc/marin3r/tls/server.key
      - ${PWD}/certs/ca.crt:/etc/marin3r/tls/ca.crt
    command:
      - marin3r
      - --log-level
      - debug
      - --namespace
      - 3scale
      - --out-of-cluster

networks:
  envoymesh: {}
