apiVersion: kuttl.dev/v1beta1
kind: TestSuite
crdDir: config/crd/bases
testDirs: [test/e2e/]
timeout: 60
startKIND: true
kindNodeCache: true
parallel: 1
artifactsDir: tmp/test
kindConfig: test/kind.yaml
manifestDirs:
- tmp/deploy/
kindContainers:
  - quay.io/3scale/marin3r:test
