apiVersion: kuttl.dev/v1beta1
kind: TestSuite
crdDir: config/crd/bases
testDirs: [test/kuttl/]
timeout: 60
startKIND: false
kindNodeCache: true
parallel: 1
artifactsDir: tmp/test
kindConfig: test/kind.yaml
manifestDirs:
- tmp/deploy/
kindContainers:
  - quay.io/3scale/marin3r:test
