apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/3scale-sre/marin3r
  newTag: v0.13.4
resources:
- manager.yaml

patches:
- path: custom/manager_patch.yaml
