apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: discoveryservicecertificates.operator.marin3r.3scale.net
spec:
  group: operator.marin3r.3scale.net
  names:
    kind: DiscoveryServiceCertificate
    listKind: DiscoveryServiceCertificateList
    plural: discoveryservicecertificates
    singular: discoveryservicecertificate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DiscoveryServiceCertificate is used to create certificates, either
        self-signed or by using a cert-manager CA issuer. This object is used by the
        DiscoveryService controller to create the required certificates for the diferent
        components of the discovery service. Direct use of DiscoveryServiceCertificate
        objects is discouraged.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DiscoveryServiceCertificateSpec defines the desired state of
            DiscoveryServiceCertificate
          properties:
            commonName:
              description: CommonName is the CommonName of the certificate
              type: string
            hosts:
              description: Hosts is the list of hosts the certificate is valid for.
                Only use when 'IsServerCertificate' is true. If unset, the CommonName
                field will be used to populate the valid hosts of the certificate.
              items:
                type: string
              type: array
            isCA:
              description: IsCA is a boolean specifying that the certificate is a
                CA
              type: boolean
            secretRef:
              description: SecretRef is a reference to the secret that will hold the
                certificate and the private key.
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
            server:
              description: IsServerCertificate is a boolean specifying if the certificate
                should be issued with server auth usage enabled
              type: boolean
            signer:
              description: Signer specifies  the signer to use to create this certificate.
                Supported signers are CertManager and SelfSigned.
              properties:
                certManager:
                  description: CertManager holds specific configuration for the CertManager
                    signer
                  properties:
                    clusterIssuer:
                      description: The name of the cert-manager ClusterIssuer to be
                        used to sign the
                      type: string
                  required:
                  - clusterIssuer
                  type: object
                selfSigned:
                  description: SelfSigned holds specific configuration for the SelfSigned
                    signer
                  type: object
              type: object
            validFor:
              description: ValidFor specifies the validity of the certificate in seconds
              format: int64
              type: integer
          required:
          - commonName
          - secretRef
          - signer
          - validFor
          type: object
        status:
          description: DiscoveryServiceCertificateStatus defines the observed state
            of DiscoveryServiceCertificate
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
