//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/3scale-ops/marin3r/pkg/envoy"
	serializer "github.com/3scale-ops/marin3r/pkg/envoy/serializer"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigRevisionRef) DeepCopyInto(out *ConfigRevisionRef) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigRevisionRef.
func (in *ConfigRevisionRef) DeepCopy() *ConfigRevisionRef {
	if in == nil {
		return nil
	}
	out := new(ConfigRevisionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfig) DeepCopyInto(out *EnvoyConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfig.
func (in *EnvoyConfig) DeepCopy() *EnvoyConfig {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigList) DeepCopyInto(out *EnvoyConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvoyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigList.
func (in *EnvoyConfigList) DeepCopy() *EnvoyConfigList {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigRevision) DeepCopyInto(out *EnvoyConfigRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigRevision.
func (in *EnvoyConfigRevision) DeepCopy() *EnvoyConfigRevision {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyConfigRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigRevisionList) DeepCopyInto(out *EnvoyConfigRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvoyConfigRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigRevisionList.
func (in *EnvoyConfigRevisionList) DeepCopy() *EnvoyConfigRevisionList {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvoyConfigRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigRevisionSpec) DeepCopyInto(out *EnvoyConfigRevisionSpec) {
	*out = *in
	if in.EnvoyAPI != nil {
		in, out := &in.EnvoyAPI, &out.EnvoyAPI
		*out = new(envoy.APIVersion)
		**out = **in
	}
	if in.Serialization != nil {
		in, out := &in.Serialization, &out.Serialization
		*out = new(serializer.Serialization)
		**out = **in
	}
	if in.EnvoyResources != nil {
		in, out := &in.EnvoyResources, &out.EnvoyResources
		*out = new(EnvoyResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigRevisionSpec.
func (in *EnvoyConfigRevisionSpec) DeepCopy() *EnvoyConfigRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigRevisionStatus) DeepCopyInto(out *EnvoyConfigRevisionStatus) {
	*out = *in
	if in.Published != nil {
		in, out := &in.Published, &out.Published
		*out = new(bool)
		**out = **in
	}
	if in.ProvidesVersions != nil {
		in, out := &in.ProvidesVersions, &out.ProvidesVersions
		*out = new(VersionTracker)
		**out = **in
	}
	if in.LastPublishedAt != nil {
		in, out := &in.LastPublishedAt, &out.LastPublishedAt
		*out = (*in).DeepCopy()
	}
	if in.Tainted != nil {
		in, out := &in.Tainted, &out.Tainted
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigRevisionStatus.
func (in *EnvoyConfigRevisionStatus) DeepCopy() *EnvoyConfigRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigSpec) DeepCopyInto(out *EnvoyConfigSpec) {
	*out = *in
	if in.Serialization != nil {
		in, out := &in.Serialization, &out.Serialization
		*out = new(serializer.Serialization)
		**out = **in
	}
	if in.EnvoyAPI != nil {
		in, out := &in.EnvoyAPI, &out.EnvoyAPI
		*out = new(envoy.APIVersion)
		**out = **in
	}
	if in.EnvoyResources != nil {
		in, out := &in.EnvoyResources, &out.EnvoyResources
		*out = new(EnvoyResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigSpec.
func (in *EnvoyConfigSpec) DeepCopy() *EnvoyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyConfigStatus) DeepCopyInto(out *EnvoyConfigStatus) {
	*out = *in
	if in.CacheState != nil {
		in, out := &in.CacheState, &out.CacheState
		*out = new(string)
		**out = **in
	}
	if in.PublishedVersion != nil {
		in, out := &in.PublishedVersion, &out.PublishedVersion
		*out = new(string)
		**out = **in
	}
	if in.DesiredVersion != nil {
		in, out := &in.DesiredVersion, &out.DesiredVersion
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigRevisions != nil {
		in, out := &in.ConfigRevisions, &out.ConfigRevisions
		*out = make([]ConfigRevisionRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyConfigStatus.
func (in *EnvoyConfigStatus) DeepCopy() *EnvoyConfigStatus {
	if in == nil {
		return nil
	}
	out := new(EnvoyConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyResource) DeepCopyInto(out *EnvoyResource) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyResource.
func (in *EnvoyResource) DeepCopy() *EnvoyResource {
	if in == nil {
		return nil
	}
	out := new(EnvoyResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyResources) DeepCopyInto(out *EnvoyResources) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScopedRoutes != nil {
		in, out := &in.ScopedRoutes, &out.ScopedRoutes
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Runtimes != nil {
		in, out := &in.Runtimes, &out.Runtimes
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]EnvoySecretResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtensionConfigs != nil {
		in, out := &in.ExtensionConfigs, &out.ExtensionConfigs
		*out = make([]EnvoyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyResources.
func (in *EnvoyResources) DeepCopy() *EnvoyResources {
	if in == nil {
		return nil
	}
	out := new(EnvoyResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoySecretResource) DeepCopyInto(out *EnvoySecretResource) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoySecretResource.
func (in *EnvoySecretResource) DeepCopy() *EnvoySecretResource {
	if in == nil {
		return nil
	}
	out := new(EnvoySecretResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenerateFromEndpointSlices) DeepCopyInto(out *GenerateFromEndpointSlices) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenerateFromEndpointSlices.
func (in *GenerateFromEndpointSlices) DeepCopy() *GenerateFromEndpointSlices {
	if in == nil {
		return nil
	}
	out := new(GenerateFromEndpointSlices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.GenerateFromTlsSecret != nil {
		in, out := &in.GenerateFromTlsSecret, &out.GenerateFromTlsSecret
		*out = new(string)
		**out = **in
	}
	if in.GenerateFromOpaqueSecret != nil {
		in, out := &in.GenerateFromOpaqueSecret, &out.GenerateFromOpaqueSecret
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.GenerateFromEndpointSlices != nil {
		in, out := &in.GenerateFromEndpointSlices, &out.GenerateFromEndpointSlices
		*out = new(GenerateFromEndpointSlices)
		(*in).DeepCopyInto(*out)
	}
	if in.Blueprint != nil {
		in, out := &in.Blueprint, &out.Blueprint
		*out = new(Blueprint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionTracker) DeepCopyInto(out *VersionTracker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionTracker.
func (in *VersionTracker) DeepCopy() *VersionTracker {
	if in == nil {
		return nil
	}
	out := new(VersionTracker)
	in.DeepCopyInto(out)
	return out
}
