apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: marin3r-webhook-service
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    control-plane: controller-webhook
status:
  loadBalancer: {}
