apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  podMetricsEndpoints:
    - interval: 10s
      path: /stats/prometheus
      port: envoy-metrics
      scheme: http
  selector:
    matchLabels:
      app: kuard
