{
 "title": "3scale Limitador",
 "tags": [
  "3scale",
  "backend"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(limitador_up,namespace)"
   },
   { "name": "deployment", "label": "component", "query": "limitador,kuard,redis" },
   {
    "name": "limitador_namespace",
    "label": "limitador_namespace",
    "query": "label_values(authorized_calls{namespace=\"$namespace\"},limitador_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kuard Envoyproxy Sidecar metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests per second (global)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ratelimit_ok{namespace=\"$namespace\", envoy_cluster_name=\"$limitador_namespace\"}[1m]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(envoy_cluster_ratelimit_over_limit{namespace=\"$namespace\", envoy_cluster_name=\"$limitador_namespace\"}[1m]))",
     "legendFormat": "overlimit"
    }
   ]
  },
  {
   "title": "Requests per second (per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_ratelimit_ok{namespace=\"$namespace\", envoy_cluster_name=\"$limitador_namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}-ok"
    },
    {
     "expr": "sum(rate(envoy_cluster_ratelimit_over_limit{namespace=\"$namespace\", envoy_cluster_name=\"$limitador_namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}-over-limit"
    }
   ]
  },
  { "title": "Limitador metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Requests per second (global)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(authorized_calls{namespace=\"$namespace\", limitador_namespace=\"$limitador_namespace\"}[1m]))",
     "legendFormat": "authorized"
    },
    {
     "expr": "sum(rate(limited_calls{namespace=\"$namespace\", limitador_namespace=\"$limitador_namespace\"}[1m]))",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Requests per second (per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(authorized_calls{namespace=\"$namespace\", limitador_namespace=\"$limitador_namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}-authorized"
    },
    {
     "expr": "sum(rate(limited_calls{namespace=\"$namespace\", limitador_namespace=\"$limitador_namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}-limited"
    }
   ]
  },
  { "title": "Pods ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "deployment" },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment='$deployment'}) or kube_statefulset_status_replicas {namespace='$namespace',statefulset='$deployment'}"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment='$deployment'}) or (kube_statefulset_status_replicas {namespace='$namespace',statefulset='$deployment'} - kube_statefulset_status_replicas_ready {namespace='$namespace',statefulset='$deployment'} )"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-.*'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-.*'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace='$namespace',deployment='$deployment'} or kube_statefulset_status_replicas {namespace='$namespace',statefulset='$deployment'}",
     "legendFormat": "total-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment='$deployment'} or kube_statefulset_status_replicas_ready {namespace='$namespace',statefulset='$deployment'}",
     "legendFormat": "-avail-pods"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment='$deployment'} or (kube_statefulset_status_replicas {namespace='$namespace',statefulset='$deployment'} - kube_statefulset_status_replicas_ready {namespace='$namespace',statefulset='$deployment'} )",
     "legendFormat": "unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace='$namespace',pod=~'$deployment-.*'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 }, "repeat": "deployment" },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 }, "repeat": "deployment" },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 }, "repeat": "deployment" },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$deployment-.*', container!=''}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Quota ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 }, "repeat": "deployment" },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-.*', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod!~'.*redis.*',pod=~'$deployment-.*', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace',pod=~'$deployment-.*', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-.*'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage ($deployment)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }, "repeat": "deployment" },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace',pod=~'$deployment-.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace',pod=~'$deployment-.*'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}