apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-webhook
  namespace: system
  labels:
    control-plane: controller-webhook
spec:
  selector:
    matchLabels:
      control-plane: controller-webhook
  replicas: 2
  template:
    metadata:
      labels:
        control-plane: controller-webhook
    spec:
      containers:
      - name: webhook
        image: controller:latest
        command:
        - /manager
        args:
        - webhook
        - --tls-dir=/tmp/k8s-webhook-server/serving-certs
        - --tls-cert-name=tls.crt
        - --tls-key-name=tls.key
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
