
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: sidecar-injector.marin3r.3scale.net
    sideEffects: None
    clientConfig:
      caBundle: Cg==
      service:
        name: webhook-service
        namespace: system
        path: /pod-v1-mutate
        port: 9443
    reinvocationPolicy: Never
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ''
        apiVersions:
          - v1
        resources:
          - pods
        scope: Namespaced
    matchPolicy: Equivalent
    admissionReviewVersions: ["v1"]
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        marin3r.3scale.net/status: enabled
    timeoutSeconds: 5