apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
- ../webhook

# Adds namespace to all resources.
namespace: marin3r-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: marin3r-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue


  # Protect the /metrics endpoint by putting it behind auth.
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, please comment the following lines.
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: controller-manager
    namespace: system
  spec:
    template:
      spec:
        containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          args:
          - "--secure-listen-address=0.0.0.0:8443"
          - "--upstream=http://127.0.0.1:8080/"
          - "--logtostderr=true"
          - "--v=10"
          ports:
          - containerPort: 8443
            name: https
        - name: manager
          args:
          - operator
          - "--metrics-bind-address=127.0.0.1:8080"
          - "--leader-elect"

patches:
- patch: |-
    - op: remove
      path: /spec/template/spec/volumes
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts
  target:
    group: apps
    kind: Deployment
    name: controller-webhook
    version: v1
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - webhook
      - --tls-dir=/apiserver.local.config/certificates
      - --tls-cert-name=apiserver.crt
      - --tls-key-name=apiserver.key
  target:
    group: apps
    kind: Deployment
    name: controller-webhook
    version: v1
