apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
- ../webhook

namespace: marin3r-system
namePrefix: marin3r-

patchesStrategicMerge:
  - manager_patch.yaml

patches:
- path: manager_patch.yaml
  target:
    kind: Deployment
    name: controller-manager
- path: webhook_patch.yaml
  target:
    kind: Deployment
    name: controller-webhook
- path: metrics_service_patch.yaml
  target:
    kind: Service
    name: controller-manager-metrics-service
