# Adds namespace to all resources.
namespace: marin3r-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: marin3r-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
  - ../crd
  - ../rbac
  - ../manager
  - ../webhook

patchesStrategicMerge:
  # Protect the /metrics endpoint by putting it behind auth.
  # If you want your controller-manager to expose the /metrics
  # endpoint w/o any authn/z, please comment the following lines.
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
      namespace: system
    spec:
      template:
        spec:
          containers:
          - name: kube-rbac-proxy
            image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
            args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
            ports:
            - containerPort: 8443
              name: https
          - name: manager
            args:
            - operator
            - "--metrics-addr=127.0.0.1:8080"
            - "--enable-leader-election"

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-webhook
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts