apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../crd
- ../rbac
- ../manager
- ../webhook

namespace: marin3r-system
namePrefix: marin3r-

patches:
- path: webhook_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-webhook
    version: v1
