version: 2.1
workflows:
  test-and-release:
    jobs:
      - test:
          filters: # required since `release` has tag filters AND requires `test`
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  test: # runs not using Workflows must have a `build` job as entry point
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.13

    steps: # steps that comprise the `build` job
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run:
          name: Run unit tests
          command: make test

      - run: make build
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  release:
    docker:
      - image: circleci/golang:1.14-buster
        environment:
          IMAGE_NAME: quay.io/3scale/marin3r
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          RELEASE=${CIRCLE_TAG}
          make docker-build IMAGE_NAME=${IMAGE_NAME} RELEASE=${RELEASE}
          echo ${QUAY_PASSWD} | docker login quay.io -u ${QUAY_USER} --password-stdin
          docker push ${IMAGE_NAME}:${RELEASE}