version: 2.1
workflows:
  test-and-release:
    jobs:
      - unit-test:
          filters: # required since `release` has tag filters AND requires `test`
            tags:
              only: /.*/
      - release:
          requires:
            - unit-test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  unit-test:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.13

    environment:
      TEST_CPUS: 2

    steps: # steps that comprise the `build` job
      - checkout

      # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - pkg-cache

      - run:
          name: Run unit tests
          command: make unit-test

      # Store cache in the /go/pkg directory
      - save_cache:
          key: pkg-cache
          paths:
            - "/go/pkg"

  release:
    docker:
      - image: circleci/golang:1.13
        environment:
          IMAGE_NAME: quay.io/3scale/marin3r
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          RELEASE=${CIRCLE_TAG}
          make docker-build IMAGE_NAME=${IMAGE_NAME} RELEASE=${RELEASE}
          echo ${QUAY_PASSWD} | docker login quay.io -u ${QUAY_USER} --password-stdin
          docker push ${IMAGE_NAME}:${RELEASE}
