# permissions for end users to view discoveryservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discoveryservice-viewer-role
rules:
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - discoveryservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - discoveryservices/status
  verbs:
  - get
