# permissions for end users to edit envoydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoydeployment-editor-role
rules:
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments/status
  verbs:
  - get
