# permissions for end users to view envoyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoyconfig-viewer-role
rules:
- apiGroups:
  - envoy.marin3r.3scale.net
  resources:
  - envoyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - envoy.marin3r.3scale.net
  resources:
  - envoyconfigs/status
  verbs:
  - get
