# permissions for end users to view envoyconfigrevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoyconfigrevision-viewer-role
rules:
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions/status
  verbs:
  - get
