# permissions for end users to view envoydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoydeployment-viewer-role
rules:
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.marin3r.3scale.net
  resources:
  - envoydeployments/status
  verbs:
  - get
