# permissions for end users to edit envoyconfigrevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: envoyconfigrevision-editor-role
rules:
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - marin3r.3scale.net
  resources:
  - envoyconfigrevisions/status
  verbs:
  - get
