resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
# (2021-02-23) Temporarily remove the auth proxy metrics reader service
# Due to a bug in OLM where upgrading a CSV fails when providing
# a Service object as part of the bundle manifests. We should reenable this
# once that bug is fixed
# - auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml
