apiVersion: marin3r.3scale.net/v1alpha1
kind: EnvoyConfig
metadata:
  name: kuard
spec:
  nodeID: kuard
  resources:
    - type: listener
      value:
        name: https
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8443
        filter_chains:
          - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  access_log:
                    - name: envoy.access_loggers.file
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /dev/stdout
                  stat_prefix: ingress_http
                  rds:
                    route_config_name: "kuard"
                    config_source:
                      ads: {}
                      resource_api_version: "V3"
                  http_filters:
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  tls_certificate_sds_secret_configs:
                    - name: kuard
                      sds_config:
                        ads: {}
                        resource_api_version: "V3"
    - type: secret
      generateFromTlsSecret: kuard
    - type: route
      value:
        name: kuard
        virtual_hosts:
          - name: all
            domains: ["*"]
            routes:
              - match:
                  prefix: "/"
                route:
                  cluster: "kuard"
    - type: cluster
      value:
        name: kuard
        connect_timeout: 0.010s
        type: EDS
        lb_policy: ROUND_ROBIN
        eds_cluster_config:
          eds_config:
            ads: {}
            resource_api_version: "V3"
    - type: endpoint
      generateFromEndpointSlices:
        selector:
          matchLabels:
            kubernetes.io/service-name: kuard
        clusterName: kuard
        targetPort: http
