// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerConfig) DeepCopyInto(out *CertManagerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerConfig.
func (in *CertManagerConfig) DeepCopy() *CertManagerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertManagerSignerConfig) DeepCopyInto(out *CertManagerSignerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertManagerSignerConfig.
func (in *CertManagerSignerConfig) DeepCopy() *CertManagerSignerConfig {
	if in == nil {
		return nil
	}
	out := new(CertManagerSignerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryService) DeepCopyInto(out *DiscoveryService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryService.
func (in *DiscoveryService) DeepCopy() *DiscoveryService {
	if in == nil {
		return nil
	}
	out := new(DiscoveryService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceCertificate) DeepCopyInto(out *DiscoveryServiceCertificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceCertificate.
func (in *DiscoveryServiceCertificate) DeepCopy() *DiscoveryServiceCertificate {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryServiceCertificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceCertificateList) DeepCopyInto(out *DiscoveryServiceCertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveryServiceCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceCertificateList.
func (in *DiscoveryServiceCertificateList) DeepCopy() *DiscoveryServiceCertificateList {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceCertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryServiceCertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceCertificateSigner) DeepCopyInto(out *DiscoveryServiceCertificateSigner) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerConfig)
		**out = **in
	}
	if in.SelfSigned != nil {
		in, out := &in.SelfSigned, &out.SelfSigned
		*out = new(SelfSignedConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceCertificateSigner.
func (in *DiscoveryServiceCertificateSigner) DeepCopy() *DiscoveryServiceCertificateSigner {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceCertificateSigner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceCertificateSpec) DeepCopyInto(out *DiscoveryServiceCertificateSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Signer.DeepCopyInto(&out.Signer)
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceCertificateSpec.
func (in *DiscoveryServiceCertificateSpec) DeepCopy() *DiscoveryServiceCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceCertificateStatus) DeepCopyInto(out *DiscoveryServiceCertificateStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceCertificateStatus.
func (in *DiscoveryServiceCertificateStatus) DeepCopy() *DiscoveryServiceCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceCertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceList) DeepCopyInto(out *DiscoveryServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveryService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceList.
func (in *DiscoveryServiceList) DeepCopy() *DiscoveryServiceList {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceSpec) DeepCopyInto(out *DiscoveryServiceSpec) {
	*out = *in
	if in.EnabledNamespaces != nil {
		in, out := &in.EnabledNamespaces, &out.EnabledNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Signer.DeepCopyInto(&out.Signer)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceSpec.
func (in *DiscoveryServiceSpec) DeepCopy() *DiscoveryServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServiceStatus) DeepCopyInto(out *DiscoveryServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServiceStatus.
func (in *DiscoveryServiceStatus) DeepCopy() *DiscoveryServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfSignedConfig) DeepCopyInto(out *SelfSignedConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfSignedConfig.
func (in *SelfSignedConfig) DeepCopy() *SelfSignedConfig {
	if in == nil {
		return nil
	}
	out := new(SelfSignedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignerConfig) DeepCopyInto(out *SignerConfig) {
	*out = *in
	if in.CertManager != nil {
		in, out := &in.CertManager, &out.CertManager
		*out = new(CertManagerSignerConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignerConfig.
func (in *SignerConfig) DeepCopy() *SignerConfig {
	if in == nil {
		return nil
	}
	out := new(SignerConfig)
	in.DeepCopyInto(out)
	return out
}
