apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: discoveryservices.operator.marin3r.3scale.net
spec:
  group: operator.marin3r.3scale.net
  names:
    kind: DiscoveryService
    listKind: DiscoveryServiceList
    plural: discoveryservices
    singular: discoveryservice
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DiscoveryService represents an envoy discovery service server.
        Currently only one DiscoveryService per cluster is supported.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DiscoveryServiceSpec defines the desired state of DiscoveryService
          properties:
            debug:
              description: Debug enables debugging log level for the discovery service
                controllers. It is safe to use since secret data is never shown in
                the logs.
              type: boolean
            discoveryServiceNamespace:
              description: DiscoveryServiceNamespcae is the name of the namespace
                where the envoy discovery service server should be deployed.
              type: string
            enabledNamespaces:
              description: EnabledNamespaces is a list of namespaces where the envoy
                discovery service is enabled. In order to be able to use marin3r from
                a given namespace its name needs to be included in this list because
                the operator needs to add some required resources in that namespace.
              items:
                type: string
              type: array
            image:
              description: Image holds the image to use for the discovery service
                Deployment
              type: string
          required:
          - discoveryServiceNamespace
          - image
          type: object
        status:
          description: DiscoveryServiceStatus defines the observed state of DiscoveryService
          properties:
            conditions:
              description: Conditions represent the latest available observations
                of an object's state
              items:
                description: "Condition represents an observation of an object's state.
                  Conditions are an extension mechanism intended to be used when the
                  details of an observation are not a priori known or would not apply
                  to all instances of a given Kind. \n Conditions should be added
                  to explicitly convey properties that users and components care about
                  rather than requiring those properties to be inferred from other
                  observations. Once defined, the meaning of a Condition can not be
                  changed arbitrarily - it becomes part of the API, and has the same
                  backwards- and forwards-compatibility concerns of any other part
                  of the API."
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    description: ConditionReason is intended to be a one-word, CamelCase
                      representation of the category of cause of the current status.
                      It is intended to be used in concise output, such as one-line
                      kubectl get output, and in summarizing occurrences of causes.
                    type: string
                  status:
                    type: string
                  type:
                    description: "ConditionType is the type of the condition and is
                      typically a CamelCased word or short phrase. \n Condition types
                      should indicate state in the \"abnormal-true\" polarity. For
                      example, if the condition indicates when a policy is invalid,
                      the \"is valid\" case is probably the norm, so the condition
                      should be called \"Invalid\"."
                    type: string
                required:
                - status
                - type
                type: object
              type: array
          required:
          - conditions
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
