---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marin3r-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - serviceaccounts
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - watch
      - list
      - patch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - watch
      - create
      - list
      - patch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - clusterissuers
    verbs:
      - "*"
  - apiGroups:
      - operator.marin3r.3scale.net
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - marin3r.3scale.net
    resources:
      - "*"
    verbs:
      - "*"
