---
apiVersion: v1
kind: Pod
metadata:
  name: envoy1
spec:
  containers:
    - name: envoy-sidecar
      image: envoyproxy/envoy:v1.13.1
      command: ["envoy"]
      args:
        [
          "-c",
          "/etc/envoy/bootstrap/config.yaml",
          "--service-cluster",
          "envoy1",
          "--service-node",
          "envoy1",
        ]
      ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          hostPort: 8443
          protocol: TCP
      volumeMounts:
        - name: envoy-sidecar-bootstrap
          mountPath: /etc/envoy/bootstrap
        - name: client-cert
          mountPath: /etc/envoy/tls/client
  volumes:
    - name: envoy-sidecar-bootstrap
      configMap:
        name: envoy-sidecar-bootstrap
    - name: envoy-sidecar-client-cert
      secret:
        secretName: envoy-sicecar-client-cert

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: envoy1
#   namespace: default
#   labels:
#     app: envoy1
# spec:
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 8080
#       targetPort: http
#     - name: https
#       port: 8443
#       targetPort: https
#   selector:
#     app: envoy1
