apiVersion: v1
kind: Pod
metadata:
  name: envoy1
spec:
  containers:
    - name: envoy-sidecar
      image: envoyproxy/envoy:v1.13.1
      command: ["envoy"]
      args:
        [
          "-c",
          "/etc/envoy/bootstrap/config.yaml",
          "--service-cluster",
          "roivaz",
          "--service-node",
          "roivaz",
        ]
      volumeMounts:
        - name: bootstrap
          mountPath: /etc/envoy/bootstrap
        - name: client-cert
          mountPath: /etc/envoy/tls/client
  volumes:
    - name: bootstrap
      configMap:
        name: envoy-bootstrap
    - name: client-cert
      secret:
        secretName: envoy-client-cert
