## Append samples you want in your CSV to this file as resources ##
resources:
- operator.marin3r_v1alpha1_discoveryservice.yaml
- operator.marin3r_v1alpha1_envoydeployment.yaml
- marin3r_v1alpha1_envoyconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
