apiVersion: operator.marin3r.3scale.net/v1alpha1
kind: EnvoyDeployment
metadata:
  name: envoydeployment-sample
  namespace: my-namespace
spec:
  discoveryServiceRef: discoveryservice-example
  envoyConfigRef: envoyconfig-example
  ports:
    - name: https
      port: 8443
