---
apiVersion: operator.marin3r.3scale.net/v1alpha1
kind: DiscoveryServiceCertificate
metadata:
  name: example
  namespace: my-namespace
spec:
  commonName: test-client
  validFor: 3600
  signer:
    certManager:
      clusterIssuer: marin3r-instance
  secretRef:
    name: test-cert
    namespace: default