apiVersion: operator.marin3r.3scale.net/v1alpha1
kind: EnvoyDeployment
metadata:
  name: envoydeployment-sample
spec:
  envoyConfigRef: example
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8443
