apiVersion: v1
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWVENDQWoyZ0F3SUJBZ0lRUld4a1pDTi8w
    VEJSYzV6VTVTVEZJakFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFEREFoRGFHRnVa
    MlZOWlRBZUZ3MHlNREEwTWpBeE5qRTRORGhhRncweU16QTBNRFV4TmpFNApORGhhTUJneEZqQVVC
    Z05WQkFNTURXVnVkbTk1TFhObGNuWmxjakl3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJE
    d0F3Z2dFS0FvSUJBUUNudFdScTVOSW5LaWllVkJWUHNBcjZDc0tHQVlEY0dlVEdoOFNNSFV0WnBB
    NEUKYkM2dC9tMXlBdHhqallqK2dObVQ2VEF3U1NyVEJGaHpCeGhFTG03bER0VVRramJVYXFNMHIy
    eExsQkg5UERtSAovajhJUmRhdXUxdU1wRk8ySVFkYXhKRGlLdXNoRjl2Y0M5dEthZkFNcSsxUFEv
    MDFBTlVrN1BBSWc2NnMxcWxvClo5WUFjVUU3dDdNN3NOUGc2TGFEMHJQdUZXakkxUFZwalpLTEh0
    TzBnN3FnVXJ5bk1oZmxEODRSTmdhMmJpVXkKY3lpSlEwaFZFZEU0MFdqanFFUStkSFd4TTlhc2R5
    cUp1UHZER1lDSXFYeG9VaGtIWldIdUJ1NDRCTjJCTjlTaQpyZFBGZWFRdENTeXVBcnI0aDJxS1VL
    UE1mMUhsV1kwUUcvOFJ6L2gzQWdNQkFBR2pnWjh3Z1p3d0NRWURWUjBUCkJBSXdBREFkQmdOVkhR
    NEVGZ1FVNWx3ZHFQRzZiVlBnK3hPV3lyVmdVeDJiZjMwd1RnWURWUjBqQkVjd1JZQVUKcWx6RnRv
    bDJFTlNHRC91ME5GUERjdHRnZC9XaEY2UVZNQk14RVRBUEJnTlZCQU1NQ0VOb1lXNW5aVTFsZ2hR
    eQozOHVLYUFaazBKVHNxWUVYUGg3SW1mSGQ3VEFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQWpB
    TEJnTlZIUThFCkJBTUNCNEF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUF5ZW5RbHZ1ZkU5VlNk
    MjlFUlVWQSsyc052MXJKZTIKNHBrTWRzTkd3RWoxVVpxdVVwUXBNNGZXNWpqc3dZdVRKMVRNa3Iv
    Yk1ia3lyb05iSUdoeUJlU3A4VTNOdGFqMQpPMFJ4MVR6UEhwWDVIb29EMGNTc2s4MzAwYXArVzdp
    Uy85dFI0STN4TVFHWXFON1RqNCt1RmltSFlEcEVEMUg3CldNWXdwV3d5blpaUnoyajlEUENWY0JR
    cFdyQ09jTU5zb0ZnRWVMOHdHbGZYL1MxZUZpelRSeWlwMldGVUtyU2oKS3NiUExXbVlEUmVWSWJR
    S1c4Zm9KNDYzRlhtbXVLV2ZVRTh3VjBBdjFZVkRhQ2Jsa0xYb1hId2pBSFRybU5SbApUaGFWckIv
    RDBQQ3hzK1U1NHdETDRIckFPUkl4ZDBOdlk0eC9MbUd2Y01JM1pWN2VUdUh1MUg4PQotLS0tLUVO
    RCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ250V1JxNU5JbktpaWUKVkJWUHNBcjZDc0tHQVlEY0dlVEdo
    OFNNSFV0WnBBNEViQzZ0L20xeUF0eGpqWWorZ05tVDZUQXdTU3JUQkZoegpCeGhFTG03bER0VVRr
    amJVYXFNMHIyeExsQkg5UERtSC9qOElSZGF1dTF1TXBGTzJJUWRheEpEaUt1c2hGOXZjCkM5dEth
    ZkFNcSsxUFEvMDFBTlVrN1BBSWc2NnMxcWxvWjlZQWNVRTd0N003c05QZzZMYUQwclB1RldqSTFQ
    VnAKalpLTEh0TzBnN3FnVXJ5bk1oZmxEODRSTmdhMmJpVXljeWlKUTBoVkVkRTQwV2pqcUVRK2RI
    V3hNOWFzZHlxSgp1UHZER1lDSXFYeG9VaGtIWldIdUJ1NDRCTjJCTjlTaXJkUEZlYVF0Q1N5dUFy
    cjRoMnFLVUtQTWYxSGxXWTBRCkcvOFJ6L2gzQWdNQkFBRUNnZ0VBVVI0UW93OW9ncDhHcElaQkJK
    ayt4ZkI4WkRySDdDM3VGUVRJVVlrOXorN2wKQk1pYXozZlgwaVNHR3ZUemhUNG5mejUwRzNiWWF0
    YVlQWkw1N3NpU3hPSW10OStwKzVaVXVILzlIcFZSR2k2TwpHVFFsb3NlODdpa2JQK3lmdk9FKzRH
    MWhNclBWcE4wWWI5ZWdTdDd3eUFCRXVXbEdTT1BOTko0Ui85eEptYmsxCjR0ZkdEZTFHTGxsaEtx
    SjJnR2dMUDlpZ3FoQStMZG9WcjFSMmxYRUpwRy9DU1VXRVZaNTJMRys5bUp0L09ZWFcKNmp6TkEx
    QjBSS1ZGc0VMVjZuRFQ5UDgxQUhXYjltaVc5T1BTaGFabEtXaHZWTzVINnJFY1VGYW0xeGFWSkM5
    ZQpXbVdaR3NmZFB0ZXV1bDRPbnhuMlVvWUY2Zmp6ZTVITWNaRHBzR2tva1FLQmdRRGFQR0oxWjRa
    Z0RUUXYzbDJICllvUlZiQkYzc2xycHFGbENIZTQ5SDIzZXdsSU9IbHUvTEpKdGtjZzAzNmg5OXZK
    V24xZVhDbEttRlNPK3Y0aXkKcXcvaitlRDNMMVVKM3NyZjhyMmR3dlViazdvbURoV1NaQllyNXlV
    UGZaR2UwcXYrbGdscXNlSng2L3hGci93SAp5MXlzUU9BM2FYQTNGVisyZlRpdXZlZ0I2UUtCZ1FE
    RXVyT3FZYnRWNWdrVjN0bkhWcGp3djdwUmNYdWRlOUg2CnlkOXMyNTU4aFlNMkJtTlRCczdVcE9t
    SGdSL2xiNGZ6SEJRT1FKOC9ZZ25aek9nS2hBanRkQXVicGVpTmFDMkwKVXFVV25RQ1dTVTdLQzdt
    YmtqQXF2OHhHQVgvRTBVQ3JOVkk5MWJKWTlOekJ3djRiYjVRNFZjS2lGNWNYbkRESgpkSm1tbmVo
    TFh3S0JnR0Vuc00yRG9SYnh5ZUhscE0yNDFpRVJVMVZ1V1hyY0w2QjNvckFqWmM1ZHhCbjArZk5K
    CjdJWksrRTVSbzdrd1R3S3hQVlZJaXpMVkJtek02QlppZ1ZpRXpkbzlnQ1k4d1NTaDlEaGZxcTcw
    UFZMandrYkIKdC8wamtpUXJTc0RpR1IvbHU1dDhSY3RodTVWcW0xRDgvK3pQbFFJV05wYlBOU1VR
    NmtNZzJFREJBb0dBSlVxYQoyaFpTazVMYWNBbmhVRmNMQUwvblNwN3Zac2ZjNHVRM2RRUWdnOHd2
    TmlONTJuZzA1cndvQkdhbXJEQTdIZ3RaCmhlWWNDY0RFeTBON1ROc0FjanFJSk1ZTFVocklYMXVZ
    TGJRdk0wM01JS0tlV1c0WnNWRFFJUWtSdGpaUVF1UUYKcGZFSE1MT2gwUnpzWERrSGFMSmhCYWJo
    SGptZVNlSFBhblVPWHBNQ2dZQkkzSEJsSW96ek1VSFlSQW1oU0gxYQpPOFk1WmZZTEVUWE1QWTQ1
    ZlFxSlFUdEhaMUdIRjVRWkJNdml1Mmp3dngxd281V2pKaGVhTTI2Ly9MR0ZkaCtsCi93RUY4ai9q
    c2RFLzF4YVI5OURHam92UWRUNlZmei9Ya1l2MUhLTXg0VXl6V21xTEJJMC9YakJQQjJjTk02TDEK
    eHlTektWcmdNWjJTRG8rNEVIU2lzUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: envoy1-cert
  namespace: default
type: kubernetes.io/tls
