apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: discoveryservicecertificates.operator.marin3r.3scale.net
spec:
  group: operator.marin3r.3scale.net
  names:
    kind: DiscoveryServiceCertificate
    listKind: DiscoveryServiceCertificateList
    plural: discoveryservicecertificates
    singular: discoveryservicecertificate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DiscoveryServiceCertificate is used to create certificates, either
        self-signed or by using a cert-manager CA issuer. This object is used by the
        DiscoveryService controller to create the required certificates for the diferent
        components of the discovery service. Direct use of DiscoveryServiceCertificate
        objects is discouraged.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DiscoveryServiceCertificateSpec defines the desired state of
            DiscoveryServiceCertificate
          properties:
            commonName:
              type: string
            hosts:
              items:
                type: string
              type: array
            isCA:
              type: boolean
            secretRef:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
            server:
              type: boolean
            signer:
              description: DiscoveryServiceCertificateSigner specifies the signer
                to use to provision the certificate
              properties:
                certManager:
                  description: CertManagerConfig is used to generate certificates
                    using the given cert-manager issuer
                  properties:
                    clusterIssuer:
                      type: string
                  required:
                  - clusterIssuer
                  type: object
                selfSigned:
                  description: SelfSignedConfig is an empty struct to refer to the
                    selfsiged certificates provisioner
                  type: object
              type: object
            validFor:
              format: int64
              type: integer
          required:
          - commonName
          - secretRef
          - signer
          - validFor
          type: object
        status:
          description: DiscoveryServiceCertificateStatus defines the observed state
            of DiscoveryServiceCertificate
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
