apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: marin3r-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/roivaz/marin3r-catalog:latest
  displayName: Marin3r Catalog
  publisher: Red Hat
  updateStrategy:
    registryPoll:
      interval: 1m