apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: marin3r
  namespace: marin3r-system
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: marin3r
  source: marin3r-catalog
  sourceNamespace: marin3r-system