apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: marin3r
  namespace: marin3r
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: marin3r
  source: threescale-ops-source
  sourceNamespace: openshift-marketplace