name: catalog

on:
  push:
    branches:
    - main
    paths:
    - catalog/marin3r/stable-channel.yaml

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to quay.io/3scale
        if: ${{ env.NEW_RELEASE != '' }}
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & push catalog
        run: make catalog-publish
