name: test

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
jobs:
  test:
    if: ${{ github.event.label.name == 'ok-to-test' }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.10"

      - name: Run tests
        run: |
          make test
