---
apiVersion: operator.marin3r.3scale.net/v1alpha1
kind: DiscoveryService
metadata:
  name: instance
spec:
  image: localhost:5000/marin3r:test
  discoveryServiceNamespace: marin3r
  debug: true
  signer:
    certManager:
      namespace: cert-manager
  enabledNamespaces:
    - app-namespace
